# Force Quarkus to use Virtual Threads for all compatible tasks
quarkus.scheduler.use-virtual-threads=true
quarkus.rest.events.use-virtual-threads=true
# Updated standard for Quarkus 3.x+
quarkus.virtual-threads.enabled=true
quarkus.live-reload.instrumental=true

# Database connection settings
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=jgfurlan
quarkus.datasource.password=Uno234$$6
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/neurotask

# Drop and create the database at startup (useful for development)
quarkus.hibernate-orm.database.generation=drop-and-create
# Give the local Llama model up to 60 seconds to respond
quarkus.langchain4j.geminiai.timeout=60s

# Connect to the Gemini API
quarkus.langchain4j.ai.gemini.api-key=AIzaSyDeeNtdHPkpV3_0ZtkiDDWpj4US4kjssFA

# Specify the frontier model
# Point the agent to the current active API generation
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash

quarkus.analytics.disabled=false

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

%dev.quarkus.datasource.dev-ui.allow-sql=true

